development:
  cloud_name: ddxy8cp71
  api_key: 782614819676916
  api_secret: Y4lmHnbAoulogURo5QVA8-JyjD4
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: ddxy8cp71
  api_key: 782614819676916
  api_secret: Y4lmHnbAoulogURo5QVA8-JyjD4
  secure: true
  cdn_domain: true
  enhance_image_tag: true
  static_file_support: true